imports:
  - { resource: services_cron.yml }

services:
  shopsys.product_feed.heureka_bundle.feed_config:
    class: Shopsys\ProductFeed\HeurekaBundle\HeurekaFeedConfig
    tags:
      - { name: shopsys.product_feed }

  shopsys.product_feed.heureka_bundle.product_crud_extension:
    class: Shopsys\ProductFeed\HeurekaBundle\Model\Product\ProductCrudExtension
    tags:
      - { name: shopsys.crud_extension, type: product }

  shopsys.product_feed.heureka_bundle.product_form_type:
    class: Shopsys\ProductFeed\HeurekaBundle\Model\Product\ProductFormType
    tags:
      - { name: form.type }

  shopsys.product_feed.heureka_bundle.product_data_fixture:
    class: Shopsys\ProductFeed\HeurekaBundle\Model\Product\ProductDataFixture
    tags:
      - { name: shopsys.data_fixture }

  shopsys.product_feed.heureka_bundle.category_crud_extension:
    class: Shopsys\ProductFeed\HeurekaBundle\Model\Category\CategoryCrudExtension
    tags:
      - { name: shopsys.crud_extension, type: category }

  shopsys.product_feed.heureka_bundle.category_form_type:
    class: Shopsys\ProductFeed\HeurekaBundle\Model\Category\CategoryFormType
    tags:
      - { name: form.type }

  shopsys.product_feed.heureka_bundle.category_data_fixture:
    class: Shopsys\ProductFeed\HeurekaBundle\Model\Category\CategoryDataFixture
    tags:
      - { name: shopsys.data_fixture }

  shopsys.product_feed.heureka_bundle.heureka_category_downloader:
    class: Shopsys\ProductFeed\HeurekaBundle\Model\HeurekaCategory\HeurekaCategoryDownloader
    arguments:
      - '%shopsys.product_feed.heureka_bundle.heureka_category_feed_url%'

  shopsys.product_feed.heureka_bundle.heureka_category_data_fixture:
    class: Shopsys\ProductFeed\HeurekaBundle\Model\HeurekaCategory\HeurekaCategoryDataFixture
    tags:
      - { name: shopsys.data_fixture }
